apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redis-db
  namespace: redis-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: redis-db
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
