apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-db
  namespace: redis-platform
spec:
  serviceName: redis-db
  replicas: 1
  selector:
    matchLabels: { app: redis-db }
  template:
    metadata:
      labels: { app: redis-db }
    spec:
      containers:
        - name: redis
          image: docker.io/bitnamilegacy/redis:7.2.5-debian-12-r6
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef: { name: redis-db-auth, key: redis-password }
            - name: REDIS_AOF_ENABLED
              value: "yes"
            - name: REDIS_EXTRA_FLAGS
              value: "--appendfsync everysec"
          ports: [{ containerPort: 6379 }]
          resources:
            requests: { cpu: 200m, memory: 512Mi }
            limits: { cpu: 1, memory: 1Gi }
          volumeMounts:
            - name: data
              mountPath: /bitnami/redis/data
          livenessProbe:
            exec:
              command: ["redis-cli", "-a", "$(REDIS_PASSWORD)", "--no-auth-warning", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "-a", "$(REDIS_PASSWORD)", "--no-auth-warning", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs-storage
        resources: { requests: { storage: 10Gi } }
