apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-db-appl
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: redis-project
  source:
    repoURL: 'https://github.com/esarath/redis-gitops.git'
    targetRevision: main
    path: apps/redis-db/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: redis-db
      jsonPointers:
        - /spec/replicas
